//ca.module
module CA
     caption "Cross Application"
     description "This is a mandatory module that provides the general ~
                  infrastructure for all other modules. It covers general setup, ~
                  system security, maintenance of essential master data for ~
                  customers, suppliers and products."

     transactions Customer Number, Supplier Number
     codes ABC Code, Buyer, Item Class, Country, Import Duty, Customer Group, ~
           Item Group(Costing Method; Rows; Columns), Supplier Group, Price Group, Materials Manager, Market, ~
           Payment Code, Project Manager, Price Category, Division,Project, Region, ~
           Section, Supercession Code, Shipping Code, Shipping Product, SIC Code, Salesperson, ~
           Customer Status, Supplier Status, Tax Code, Tax Category, Tax Scope, ~
           Territory, Unit of Measure, Warehouse
     properties base=US$
end module


